// <auto-generated />
namespace SchoolManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_AdmissionAndOthers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_AdmissionAndOthers));
        
        string IMigrationMetadata.Id
        {
            get { return "201805190517320_add_AdmissionAndOthers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
